version: "3"
services:
  redis:
    image: redis
    ports:
      - 6379:6379
    privileged: true
  mongo:
    image: mongo:4.0
    ports:
      - 27017:27017
    privileged: true
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    privileged: true

 